# Generated by Django 4.2.27 on 2026-01-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('CompanyId', models.IntegerField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=300)),
                ('ArabicName', models.CharField(blank=True, max_length=300, null=True)),
                ('Subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('Address1', models.CharField(blank=True, max_length=300, null=True)),
                ('Address2', models.CharField(blank=True, max_length=300, null=True)),
                ('Address3', models.CharField(blank=True, max_length=300, null=True)),
                ('Phone', models.CharField(blank=True, max_length=300, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=300, null=True)),
                ('Url', models.CharField(blank=True, max_length=300, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('TinNo', models.CharField(blank=True, max_length=300, null=True)),
                ('CrNo', models.CharField(blank=True, max_length=300, null=True)),
                ('LicenseNo', models.CharField(blank=True, max_length=300, null=True)),
                ('BuildingNo', models.CharField(blank=True, max_length=300, null=True)),
                ('StreetName', models.CharField(blank=True, max_length=300, null=True)),
                ('Zone', models.CharField(blank=True, max_length=300, null=True)),
                ('Area', models.CharField(blank=True, max_length=300, null=True)),
                ('City', models.CharField(blank=True, max_length=300, null=True)),
                ('State', models.CharField(blank=True, max_length=300, null=True)),
                ('District', models.CharField(blank=True, max_length=300, null=True)),
                ('PoBox', models.CharField(blank=True, max_length=300, null=True)),
                ('PlotIdentification', models.CharField(blank=True, max_length=300, null=True)),
                ('AccountNumber', models.CharField(blank=True, max_length=300, null=True)),
                ('AccountName', models.CharField(blank=True, max_length=300, null=True)),
                ('Branch', models.CharField(blank=True, max_length=300, null=True)),
                ('Ifsc', models.CharField(blank=True, max_length=300, null=True)),
                ('PayerId', models.CharField(blank=True, max_length=300, null=True)),
                ('PayerBank', models.CharField(blank=True, max_length=300, null=True)),
                ('PayerIban', models.CharField(blank=True, max_length=300, null=True)),
                ('PeriodFrom', models.DateField()),
                ('PeriodTo', models.DateField()),
                ('DefaultDb', models.SmallIntegerField(blank=True, null=True)),
                ('BusinessType', models.SmallIntegerField(choices=[(1, 'Laundry'), (2, 'Restaurant')])),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Organization',
                'ordering': ['-CreatedAt'],
            },
        ),
    ]
